---
- name: Ensure required directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ var_lib_kubernetes_dir }}"

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create nginx conf file 
  become: true
  ansible.builtin.template:
    src: "nginx.j2"
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    force: yes
    mode: '0644'

- name: Create symbolic link for nginx site configuration
  become: true
  file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    state: link

# - name: Verify nginx health endpoint
#   become: true
#   uri:
#     url: http://127.0.0.1/healthz
#     method: GET
#     headers:
#       Host: "kubernetes.default.svc.cluster.local"
#     status_code: 200
#   register: health_check
#   until: health_check.status == 200
#   retries: 3
#   delay: 5