---
- name: Create /data/certs directory on all hosts
  hosts: cluster
  become: yes
  tasks:
    - name: Ensure /data/certs directory exists
      file:
        path: /data/certs
        state: directory
        mode: '0755'