---
- name: Ensure dependencies
  hosts: localhost
  roles:
    - dependencies

- name: Generate files
  hosts: localhost
  roles:
    - generate

- name: Distribute files
  hosts: cluster
  roles:
    - distribute

- name: Install kube-components
  hosts: controllers
  pre_tasks:
    - name: Ensure directories
      become: true
      file:
        path: /etc/kubernetes/config
        state: directory
        mode: '0755'
    
    - name: Copy kubectl in /usr/local/bin
      become: true
      copy:
          src: "{{ downloads_dir }}/kubectl"
          dest: /usr/local/bin
          owner: root
          group: root
          mode: '0755'
  
  roles:
    - etcd
    - kubernetes
    - kube-controller-manager
    - kube-scheduler
    - nginx

  post_tasks:
    - name: Ensure service is enabled and running
      become: true
      block:
        - name: Reload systemd daemon
          ansible.builtin.systemd:
            daemon_reload: yes
          changed_when: false

        - name: Enable service
          ansible.builtin.systemd:
            name: "{{ item }}"
            enabled: yes
          loop:
            - etcd
            - kube-apiserver
            - kube-controller-manager
            - kube-scheduler
            - nginx

        - name: Start service
          ansible.builtin.systemd:
            name: "{{ item }}"
            state: started
          loop:
            - etcd
            - kube-apiserver
            - kube-controller-manager
            - kube-scheduler
            - nginx