---
- name: Generate files
  hosts: localhost
  roles:
    - generate

- name: Distribute files
  hosts: cluster
  roles:
    - distribute

- name: Install etcd
  hosts: controllers
  roles:
    - etcd