---
- name: Ensure dependencies
  hosts: localhost
  roles:
    - dependencies

- name: Generate files
  hosts: localhost
  roles:
    - generate

- name: Distribute files
  hosts: cluster
  roles:
    - distribute

- name: Install kube-controllers
  hosts: controllers
  pre_tasks:
    - name: Ensure directories
      become: true
      file:
        path: /etc/kubernetes/config
        state: directory
        mode: '0755'
  
  roles:
    - etcd
    - kubernetes
    - kube-controller-manager
    - kube-scheduler