- name: Reset envs
  hosts: cluster
  tasks:
    - name: Run the script
      become: true
      shell: /home/apostoliseq/reset-env.sh
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines

- name: Reset localhost
  hosts: localhost
  tasks:
    - name: Delete generated files
      shell: rm -rf {{ certs_dir }} {{ csrs_dir }}

    - name: Run the script
      shell: rm ~/.kube/config
      register: rm_output

    - name: Display script output
      debug:
        var: rm_output.stdout_lines