- name: Reset envs
  hosts: cluster
  tasks:
    - name: Run the script
      become: true
      ansible.builtin.shell: /home/apostoliseq/reset-env.sh
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines

- name: Reset localhost
  hosts: localhost
  tasks:
    - name: Delete generated files
      ansible.builtin.shell: rm -rf {{ certs_dir }} {{ csrs_dir }}
      ignore_errors: yes

    - name: Run the script
      ansible.builtin.shell: rm ~/.kube/config
      ignore_errors: yes
      register: rm_output

    - name: Display script output
      debug:
        var: rm_output.stdout_lines

    - name: Uninstall Weave Net
      shell: kubectl delete -f /tmp/weave-net.yaml

    - name: Remove /tmp/weave-net.yaml
      ansible.builtin.shell: rm /tmp/weave-net.yaml
      ignore_errors: yes