- name: Reset envs
  hosts: cluster
  tasks:
    - name: Run the script
      become: true
      shell: /home/apostoliseq/reset-env.sh
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines