---
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ csrs_dir }}"
    - "{{ certs_dir }}"

- name: Generate ca-config.json and csrs
  ansible.builtin.include_tasks:
    file: csrs.yml

- name: Generete the kube-component certificates, signed by the CA
  ansible.builtin.include_tasks:
    file: certs.yml

- name: Generate the kube-component kubeconfigs
  ansible.builtin.include_tasks:
    file: kubeconfigs.yml

- name: Generate the encryption-config.yaml
  ansible.builtin.include_tasks:
    file: encryption-config.yml