- name: Distribute controller certs
  become: true
  copy:
    src: "{{ certs_dir }}/{{ item.file }}"
    dest: "{{ item.dest }}/{{ item.file }}"
    mode: 0644
    force: false
  loop:
    - { file: "ca-key.pem", dest: "{{ certs_dir }}" }
    - { file: "ca.pem", dest: "{{ certs_dir }}" }
    - { file: "kubernetes-key.pem", dest: "{{ certs_dir }}" }
    - { file: "kubernetes.pem", dest: "{{ certs_dir }}" }
    - { file: "service-account-key.pem", dest: "{{ certs_dir }}" }
    - { file: "service-account.pem", dest: "{{ certs_dir }}" }
    - { file: "ca.pem", dest: "{{ etcd_dir }}" }
    - { file: "kubernetes-key.pem", dest: "{{ etcd_dir }}" }
    - { file: "kubernetes.pem", dest: "{{ etcd_dir }}" }

- name: Distribute controller kubeconfigs
  become: true
  copy:
    src: "{{ certs_dir }}/{{ item.0 }}"
    dest: "{{ item.1 }}/{{ item.0 }}"
    mode: 0644
    force: false
  with_nested:
    - [ "admin.kubeconfig", "kube-controller-manager.kubeconfig", "kube-scheduler.kubeconfig" ]
    - [ "{{ certs_dir }}", "{{ etcd_dir }}"]
# - name: Distribute controller kubeconfigs
#   become: true
#   copy:
#     src: "{{ certs_dir }}/{{ item.file }}"
#     dest: "{{ item.dest }}/{{ item.file }}"
#     mode: 0644
#     force: false
#   loop:
#     - { file: "admin.kubeconfig", dest: "{{ certs_dir }}" }
#     - { file: "kube-controller-manager.kubeconfig", dest: "{{ certs_dir }}" }
#     - { file: "kube-scheduler.kubeconfig", dest: "{{ certs_dir }}" }
#     - { file: "admin.kubeconfig", dest: "{{ etcd_dir }}" }
#     - { file: "kube-controller-manager.kubeconfig", dest: "{{ etcd_dir }}" }
#     - { file: "kube-scheduler.kubeconfig", dest: "{{ etcd_dir }}" }


- name: Distribute controller encryption-config.yaml
  become: true
  copy:
    src: "{{ certs_dir }}/encryption-config.yaml"
    dest: "{{ item }}/encryption-config.yaml"
    mode: 0644
    force: false
  loop:
    - "{{ certs_dir }}"
    - "{{ etcd_dir }}"

- name: Copy kubectl in /usr/local/bin
  become: true
  copy:
      src: "{{ downloads_dir }}/kubectl"
      dest: /usr/local/bin
      mode: '0755'