---
- name: Ensure etcd service is enabled and running
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      changed_when: false

    - name: Enable etcd service
      ansible.builtin.systemd:
        name: etcd
        enabled: yes

    - name: Start etcd service
      ansible.builtin.systemd:
        name: etcd
        state: started