---
- name: Ensure kube-scheduler service is enabled and running
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      changed_when: false

    - name: Enable kube-scheduler service
      ansible.builtin.systemd:
        name: kube-scheduler
        enabled: yes

    - name: Start kube-scheduler service
      ansible.builtin.systemd:
        name: kube-scheduler
        state: started