---
- name: Ensure kubernetes service is enabled and running
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      changed_when: false

    - name: Enable kubernetes service
      ansible.builtin.systemd:
        name: kubernetes
        enabled: yes

    - name: Start kubernetes service
      ansible.builtin.systemd:
        name: kubernetes
        state: started