---
- name: Ensure kube-controller-manager service is enabled and running
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      changed_when: false

    - name: Enable kube-controller-manager service
      ansible.builtin.systemd:
        name: kube-controller-manager
        enabled: yes

    - name: Start kube-controller-manager service
      ansible.builtin.systemd:
        name: kube-controller-manager
        state: started