---
- name: Copy required files to {{ kubernetes_data_dir }}
  become: true
  ansible.builtin.copy:
    src: "{{ certs_dir }}/{{ item }}"
    dest: "{{ kubernetes_data_dir }}/{{ item }}"
    remote_src: true
    mode: 0644
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem
    - encryption-config.yaml

- name: Copy kube-apiserver in /usr/local/bin
  become: true
  ansible.builtin.copy:
      src: "{{ downloads_dir }}/kube-apiserver"
      dest: /usr/local/bin
      owner: root
      group: root
      mode: '0755'

- name: Create /etc/systemd/system/kube-apiserver.service Unit file 
  become: true
  ansible.builtin.template:
    src: "kube-apiserver.j2"
    dest: /etc/systemd/system/kube-apiserver.service
    force: yes
    mode: '0644'