---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ etc_etcd_dir }}"
    - "{{ var_lib_etcd_dir }}"

- name: Untar etcd-v3.3.5-linux-amd64.tar.gz in /usr/local/bin
  become: true
  unarchive:
      src: etcd-v3.3.5-linux-amd64.tar.gz 
      dest: /usr/local/bin
      extra_opts: [--strip-components=1]
      owner: root
      group: root
      mode: '0755'

- name: Create /etc/systemd/system/etcd.service Unit file 
  become: true
  ansible.builtin.template:
    src: "{{ inventory_hostname }}.j2"
    dest: /etc/systemd/system/etcd.service
    mode: '0644'
  when: "'controller' in inventory_hostname"

# Na mpoun san handlers
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable etcd service
  become: true
  ansible.builtin.systemd:
    name: etcd
    enabled: yes

- name: Start etcd service
  become: true
  ansible.builtin.systemd:
    name: etcd
    state: started