---
- name: Ensure required directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ var_lib_kubernetes_dir }}"

- name: Copy required files to {{ var_lib_kubernetes_dir }}
  become: true
  copy:
    src: "{{ certs_dir }}/{{ item }}"
    dest: "{{ var_lib_kubernetes_dir }}/{{ item }}"
    remote_src: true
    mode: 0644
  loop:
    - ca.pem
    - ca-key.pem
    - kube-apiserver-key.pem
    - kube-apiserver.pem
    - kube-service-account-key.pem
    - kube-service-account.pem
    - encryption-config.yaml

- name: Copy kube-apiserver in /usr/local/bin
  become: true
  copy:
      src: ./downloads/kube-apiserver 
      dest: /usr/local/bin
      owner: root
      group: root
      mode: '0755'

- name: Create /etc/systemd/system/kube-apiserver.service Unit file 
  become: true
  ansible.builtin.template:
    src: "{{ inventory_hostname }}.j2"
    dest: /etc/systemd/system/kube-apiserver.service
    mode: '0644'
  when: "'controller' in inventory_hostname"

- name: Ensure kube-apiserver service is enabled and running
  become: true
  block:
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      changed_when: false

    - name: Enable kube-apiserver service
      ansible.builtin.systemd:
        name: kube-apiserver
        enabled: yes

    - name: Start kube-apiserver service
      ansible.builtin.systemd:
        name: kube-apiserver
        state: started