- name: Ensure destination directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /data/certs
    - /etc/etcd

- name: Copy certificates to /data/certs
  copy:
    src: "{{ item }}"
    dest: "/data/certs/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - ca.pem
    - ca-key.pem
    - kube-apiserver.pem
    - kube-apiserver-key.pem
    - kube-service-account.pem
    - kube-service-account-key.pem

- name: Copy certificates to /etc/etcd
  copy:
    src: "{{ item }}"
    dest: "/etc/etcd/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - ca.pem
    - ca-key.pem
    - kube-apiserver.pem
    - kube-apiserver-key.pem
    - kube-service-account.pem
    - kube-service-account-key.pem