#SPDX-License-Identifier: MIT-0
---
# etcd_dir: /etc/etcd
# certs_dir: /data/certs
# var_lib_etcd_dir: /var/lib/etcd 
# # Env vars
# export PROJECT_DIR=$HOME/projects/kubernetes-the-hard-way

# export SSH_DIR="$HOME/.ssh"

# export WORKER1_HOST=kube-worker-1
# export WORKER2_HOST=kube-worker-2
# export WORKERS=("${WORKER1_HOST}" "${WORKER2_HOST}")
# export CONTROLLER1_HOST=kube-controller-1
# export CONTROLLER2_HOST=kube-controller-2
# export CONTROLLERS=("${CONTROLLER1_HOST}" "${CONTROLLER2_HOST}")

# # Source directory for certificates
# export CERT_BASE_DIR="${PROJECT_DIR}/certs"
# # Source directory for kubeconfigs
# export KUBECONFIG_BASE_DIR="${PROJECT_DIR}/kubeconfig"
# # Source directory for the generate scripts
# export GENERATE_CERTS_BASE_DIR="${PROJECT_DIR}/generate_scripts"

# # Destination directory for certificates and encryption-config.yaml
# export CERT_CONTAINER_DIR="/data/certs /etc/etcd"
# # Destination directory for Kubeconfigs
# export KUBECONFIG_CONTAINER_DIR="/etc/etcd"

# # Common variables for certificate generation
# export PROFILE="kubernetes"

# # Kube Worker Certificates
# export WORKER1_IP="172.18.0.4"
# export WORKER2_IP="172.18.0.3"

# # CA Certificates
# # export CA_CERT_DIR="${CERT_BASE_DIR}/ca"
# export CA_CERT="${CERT_BASE_DIR}/ca.pem"
# export CA_KEY="${CERT_BASE_DIR}/ca-key.pem"
# export CA_CONFIG="${CERT_BASE_DIR}/ca-config.json"

# # Used in Kube API certificates
# export CONTROLLER1_IP="172.18.0.2"
# export CONTROLLER2_IP="172.18.0.5"
# export LOADBALANCER_IP="172.18.0.6"
# # IPs that need access to the Kubernetes API
# export CERT_HOSTNAME=10.32.0.1,${CONTROLLER1_IP},kube-controller-1,${CONTROLLER2_IP},kube-controller-2,${LOADBALANCER_IP},kube-loadbalancer,127.0.0.1,localhost,kubernetes.default

# # Used in distribute_certificates.sh
# export WORKER1_CERTS=("${CERT_BASE_DIR}/${WORKER1_HOST}-key.pem" "${CERT_BASE_DIR}/${WORKER1_HOST}.pem")
# export WORKER2_CERTS=("${CERT_BASE_DIR}/${WORKER2_HOST}-key.pem" "${CERT_BASE_DIR}/${WORKER2_HOST}.pem")
# export CONTROLLER_CERTS=("${CA_CERT}" "${CA_KEY}" "${CERT_BASE_DIR}/kube-apiserver-key.pem" "${CERT_BASE_DIR}/kube-apiserver.pem" "${CERT_BASE_DIR}/kube-service-account-key.pem" "${CERT_BASE_DIR}/kube-service-account.pem")


# # Common variables for kubeconfig generation
# export LOADBALANCER_HOST="kube-loadbalancer"
# export CLUSTER_NAME="kubernetes-the-hard-way"

# # Node Kubeconfigs
# export WORKER1_KUBECONFIGS=("${KUBECONFIG_BASE_DIR}/kube-proxy.kubeconfig" "${KUBECONFIG_BASE_DIR}/${WORKER1_HOST}.kubeconfig")
# export WORKER2_KUBECONFIGS=("${KUBECONFIG_BASE_DIR}/kube-proxy.kubeconfig" "${KUBECONFIG_BASE_DIR}/${WORKER2_HOST}.kubeconfig")
# export CONTROLLER_KUBECONFIGS=("${KUBECONFIG_BASE_DIR}/kube-admin.kubeconfig" "${KUBECONFIG_BASE_DIR}/kube-controller-manager.kubeconfig" "${KUBECONFIG_BASE_DIR}/kube-scheduler.kubeconfig")