- name: Distribute loadbalancer certs to /data/certs
  become: true
  copy:
    src: "{{ src_certs_dir }}/{{ item }}"
    dest: "{{ dest_certs_dir }}/{{ item }}"
    mode: 0644
  loop:
    - ca.pem
  when: "'loadbalancer' in inventory_hostname"

- name: Distribute loadbalancer certs to /etc/etcd
  become: true
  copy:
    src: "{{ src_certs_dir }}/{{ item }}"
    dest: "{{ etcd_dir }}/{{ item }}"
    mode: 0644
  loop:
    - ca.pem
  when: "'loadbalancer' in inventory_hostname"