---
- name: Ensure required directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ cni_config_dir }}"
    - "{{ cni_exec_dir }}"

- name: Untar cni-plugins
  become: true
  ansible.builtin.unarchive:
    src: "{{ downloads_dir }}/cni-plugins-amd64-v{{ cni_plugins_version }}.tgz"
    dest: "{{ cni_exec_dir }}"
    extra_opts: [--strip-components=1]
    mode: '0755'

- name: Create /etc/cni/net.d/10-containerd-net.conflist
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: /etc/cni/net.d/10-containerd-net.conflist
    force: yes
    mode: '0644'