---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ certs_dir }}"
    - "{{ kubeconfig_dir }}"

- name: Execute generate_ca.sh
  shell: "{{ generate_scripts_dir }}/generate_ca.sh"

- name: Find all other scripts in the generate_scripts directory
  find:
    paths: /home/apostoliseq/projects/my-ansible-project/generate_scripts
    patterns: "*.sh"
    excludes: "generate_ca.sh"  # Exclude the already executed script
  register: script_files

- name: Execute all other scripts in the generate_scripts directory
  shell: "{{ item.path }}"
  args:
    chdir: /home/apostoliseq/projects/my-ansible-project
  loop: "{{ script_files.files }}"

- name: Create the kubeconfig directory if it doesn't exist
  file:
    path: /home/apostoliseq/projects/my-ansible-project/kubeconfig
    state: directory
    mode: '0755'

# - name: Execute set_IPs_in_common_vars.sh
#   shell: .set_IPs_in_common_vars.sh

- name: Execute generate_kubeconfigs.sh
  shell: "./generate_kubeconfigs.sh"

- name: Execute generate_encryption-config.sh
  shell: "./generate_encryption-config.sh"