- name: Create ca-config.json
  ansible.builtin.template:
    src: ca-config.j2
    dest: "{{ certs_dir }}/ca-config.json"
    mode: '0644'

- name: Create -csr.json files
  ansible.builtin.template:
    src: "csr.j2"
    dest: "{{ csrs_dir }}/{{ item }}-csr.json"
    mode: '0644'
  loop: "{{ kube_components.keys() | list }}"