- name: Create ca-config.json in csr/
  ansible.builtin.template:
    src: ca-config.j2
    dest: "{{ csr_dir }}/ca-config.json"
    mode: '0644'

- name: Create -csr.json files in csr/
  ansible.builtin.template:
    src: "csr.j2"
    dest: "{{ csr_dir }}/{{ component }}-csr.json"
    mode: '0644'
  vars:
    component: "{{ item }}"
  loop: "{{ kube_components.keys() | list }}"