- name: Generate the encryption key
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key
  changed_when: false

- name: Create encryption-config.yaml
  template:
    src: encryption-config.j2
    dest: "{{ certs_dir }}/encryption-config.yaml"
    mode: 0600