- name: Generete the kubeconfigs
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ ca_pem }} \
    --embed-certs=true \
    --server=https://{{ kube_components[component].server }}:6443 \
    --kubeconfig={{ kubeconfig_dir }}/{{ component }}.kubeconfig
    
    kubectl config set-credentials {{ kube_components[component].cn }} \
    --client-certificate={{ certs_dir }}/{{ component }}.pem \
    --client-key={{ certs_dir }}/{{ component }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ kubeconfig_dir }}/{{ component }}.kubeconfig

    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user={{ kube_components[component].cn }} \
    --kubeconfig={{ kubeconfig_dir }}/{{ component }}.kubeconfig
    
    kubectl config use-context default --kubeconfig={{ kubeconfig_dir }}/{{ component }}.kubeconfig
  vars:
    component: "{{ item }}"
  loop: "{{ kube_components.keys() | list }}"