- name: Generete the system:node kube-configs
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ certs_dir }}/ca.pem \
    --embed-certs=true \
    --server=https://{{ hostvars['kube-loadbalancer']['ansible_host'] }}:6443 \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
    
    kubectl config set-credentials system:node:{{ item }} \
    --client-certificate={{ certs_dir }}/{{ item }}.pem \
    --client-key={{ certs_dir }}/{{ item }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig

    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:node:{{ item }} \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
    
    kubectl config use-context default --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
  loop:
    - kube-worker-1
    - kube-worker-2

- name: Generete the self-hosted node system kube-configs
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ certs_dir }}/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
    
    kubectl config set-credentials system:{{ item }} \
    --client-certificate={{ certs_dir }}/{{ item }}.pem \
    --client-key={{ certs_dir }}/{{ item }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig

    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:{{ item }} \
    --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig
    
    kubectl config use-context default --kubeconfig={{ kubeconfig_dir }}/{{ item }}.kubeconfig

  loop:
    - kube-controller-manager
    - kube-scheduler

- name: Generate the kube-proxy kubeconfig
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ certs_dir }}/ca.pem \
    --embed-certs=true \
    --server=https://{{ hostvars['kube-loadbalancer']['ansible_host'] }}:6443 \
    --kubeconfig={{ kubeconfig_dir }}/kube-proxy.kubeconfig
    
    kubectl config set-credentials system:kube-proxy \
    --client-certificate={{ certs_dir }}/kube-proxy.pem \
    --client-key={{ certs_dir }}/kube-proxy-key.pem \
    --embed-certs=true \
    --kubeconfig={{ kubeconfig_dir }}/kube-proxy.kubeconfig

    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=system:kube-proxy \
    --kubeconfig={{ kubeconfig_dir }}/kube-proxy.kubeconfig
    
    kubectl config use-context default --kubeconfig={{ kubeconfig_dir }}/kube-proxy.kubeconfig

- name: Generate the admin kubeconfig
  shell: |
    kubectl config set-cluster {{ cluster_name }} \
    --certificate-authority={{ certs_dir }}/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig
    
    kubectl config set-credentials admin \
    --client-certificate={{ certs_dir }}/admin.pem \
    --client-key={{ certs_dir }}/admin-key.pem \
    --embed-certs=true \
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig

    kubectl config set-context default \
    --cluster={{ cluster_name }} \
    --user=admin \
    --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig
    
    kubectl config use-context default --kubeconfig={{ kubeconfig_dir }}/admin.kubeconfig