---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ csr_dir }}"
    - "{{ certs_dir }}"
    - "{{ kubeconfig_dir }}"

- name: Create ca-config.json and -csr.json files in csr/
  ansible.builtin.include_tasks:
    file: csrs.yml

- name: Generete the kube-component certificates, signed by the CA
  ansible.builtin.include_tasks:
    file: certs.yml

- name: Generate the kube-component kubeconfig
  ansible.builtin.include_tasks:
    file: kubeconfigs.yml

- name: Generate the encryption-config.yaml
  ansible.builtin.include_tasks:
    file: encryption-config.yml